-- AlterTable
ALTER TABLE "users" ADD COLUMN     "opt1" TEXT,
ADD COLUMN     "opt2" TEXT,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "email" SET DEFAULT E'',
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "schoolId" DROP DEFAULT,
ALTER COLUMN "skill" SET DEFAULT E'',
ALTER COLUMN "skill" SET DATA TYPE TEXT;
